apiVersion: apps/v1
kind: Deployment
metadata:
  name: tina-paper
  namespace: tina-paper
  labels:
    app: tina-paper
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: tina-paper
  template:
    metadata:
      labels:
        app: tina-paper
    spec:
      containers:
      - name: tina-paper
        image: docker.io/jesse677/tina-paper:latest
        envFrom:
        - secretRef:
            name: tina-paper-secrets
        env:
        - name: PAPER_TRADING
          value: "true"
        - name: CHECK_INTERVAL_SECONDS
          value: "60"
        - name: LOG_LEVEL
          value: "INFO"
        resources:
          requests:
            cpu: 250m
            memory: 256Mi
          limits:
            cpu: "1"
            memory: 1Gi
