apiVersion: v1
kind: Service
metadata:
  name: tina-paper-metrics
  namespace: tina-paper
  labels:
    app: tina-paper
spec:
  selector:
    app: tina-paper
  ports:
  - name: metrics
    port: 9200
    targetPort: metrics
